### ISSUE TITLE
Not able to export List View for Quote

### ISSUE THREAD

**Issue by Smilefounder** [xgeek-net/salesforce-devtools#51]
Hi @xgeek-net 

Thanks a lot for the great tool and the effort to build this tool. It really helps me a lot.

Btw, I'm facing an issue to export the list view for quote object. Other objects are fine. Kindly help advice.
```
Error in event handler: TypeError: Cannot read property 'name' of undefined
    at b (<URL>)
    at y (<URL>)
    at SD_DocGenerator.exportListView (<URL>)
    at Object.callback (<URL>)
    at SD_Popup.handle (<URL>)
    at <URL>
chrome-extension://ehgmhinnhggigkogkbhnbodhbfjgncjf/popup.html#:1 Error in event handler: TypeError: Cannot read property 'name' of undefined
    at b (chrome-extension://ehgmhinnhggigkogkbhnbodhbfjgncjf/dist/js/popup.min.js:38:3210)
    at y (chrome-extension://ehgmhinnhggigkogkbhnbodhbfjgncjf/dist/js/popup.min.js:38:7039)
    at SD_DocGenerator.exportListView (chrome-extension://ehgmhinnhggigkogkbhnbodhbfjgncjf/dist/js/popup.min.js:38:8070)
    at Object.callback (chrome-extension://ehgmhinnhggigkogkbhnbodhbfjgncjf/dist/js/popup.min.js:38:27163)
    at SD_Popup.handle (chrome-extension://ehgmhinnhggigkogkbhnbodhbfjgncjf/dist/js/popup.min.js:38:23232)
    at chrome-extension://ehgmhinnhggigkogkbhnbodhbfjgncjf/dist/js/popup.min.js:39:22347
```

**Comment by takashiroo** [comment]
I also met the same problem.
Listview could not be exported if it contained an owner alias.
If absolutely necessary, a formula field can be substituted.
